import React, { useState, useEffect } from 'react';
import { Database, CheckCircle2, Cloud, Trophy, RefreshCw, X, ShieldCheck, Copy, Check } from 'lucide-react';
import {
  checkSupabaseConnection,
  getLeaderboardFromSupabase,
  saveScoreToSupabase,
  SupabaseScoreRecord,
  SUPABASE_URL
} from '../lib/supabase';
import { GameStats } from '../types';

interface SupabaseSyncModalProps {
  isOpen: boolean;
  onClose: () => void;
  lang: 'hu' | 'en';
  currentStats?: GameStats;
}

export const SupabaseSyncModal: React.FC<SupabaseSyncModalProps> = ({
  isOpen,
  onClose,
  lang,
  currentStats
}) => {
  const [activeTab, setActiveTab] = useState<'leaderboard' | 'save' | 'status' | 'sql'>('leaderboard');
  const [connectionStatus, setConnectionStatus] = useState<{
    tested: boolean;
    connected: boolean;
    projectId: string;
    message: string;
  }>({
    tested: false,
    connected: false,
    projectId: 'hdxdnrxqktxszikamnbu',
    message: 'Ellenőrzés...'
  });

  const [leaderboard, setLeaderboard] = useState<SupabaseScoreRecord[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [playerName, setPlayerName] = useState<string>('');
  const [saveSuccessMsg, setSaveSuccessMsg] = useState<string | null>(null);
  const [copiedSql, setCopiedSql] = useState<boolean>(false);

  const testConnection = async () => {
    setIsLoading(true);
    const result = await checkSupabaseConnection();
    setConnectionStatus({
      tested: true,
      connected: result.connected,
      projectId: result.projectId,
      message: result.message
    });
    const scores = await getLeaderboardFromSupabase();
    setLeaderboard(scores);
    setIsLoading(false);
  };

  useEffect(() => {
    if (isOpen) {
      testConnection();
    }
  }, [isOpen]);

  const handleSaveScore = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!currentStats) return;
    setIsLoading(true);
    const result = await saveScoreToSupabase(playerName, currentStats);
    setSaveSuccessMsg(result.message);
    const updatedScores = await getLeaderboardFromSupabase();
    setLeaderboard(updatedScores);
    setIsLoading(false);
  };

  const sqlSchemaScript = `-- Supabase SQL Schema for Restaurant Quest
CREATE TABLE IF NOT EXISTS public.scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_name TEXT NOT NULL DEFAULT 'Anonymous Diner',
  score INTEGER NOT NULL DEFAULT 0,
  wallet_dollars INTEGER NOT NULL DEFAULT 0,
  total_answered INTEGER NOT NULL DEFAULT 0,
  first_try_correct INTEGER NOT NULL DEFAULT 0,
  max_streak INTEGER NOT NULL DEFAULT 0,
  accuracy_percent INTEGER NOT NULL DEFAULT 0,
  history_summary TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS and public read/write access
ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Scores" ON public.scores FOR SELECT USING (true);
CREATE POLICY "Public Insert Scores" ON public.scores FOR INSERT WITH CHECK (true);
`;

  const copySql = () => {
    navigator.clipboard.writeText(sqlSchemaScript);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2000);
  };

  if (!isOpen) return null;

  return (
    <div
      id="modal-supabase-sync"
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-xs animate-in fade-in duration-200"
    >
      <div className="bg-slate-900 border border-slate-700 rounded-3xl w-full max-w-2xl overflow-hidden shadow-2xl flex flex-col max-h-[90vh]">
        {/* Modal Header */}
        <div className="p-5 sm:p-6 bg-gradient-to-r from-emerald-900/40 via-slate-900 to-indigo-900/40 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-emerald-500/20 border border-emerald-500/40 flex items-center justify-center text-emerald-400">
              <Database className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-lg sm:text-xl font-black text-white">
                  {lang === 'hu' ? 'Supabase Adatbázis Kapcsolat' : 'Supabase Cloud Sync'}
                </h2>
                <span className="flex items-center gap-1 px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 text-xs font-bold border border-emerald-500/30">
                  <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                  Online
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Project ID: <span className="font-mono text-emerald-300">hdxdnrxqktxszikamnbu</span>
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
            aria-label="Close"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Nav Tabs */}
        <div className="flex border-b border-slate-800 bg-slate-950/50 px-4 pt-2 gap-1 text-xs sm:text-sm">
          <button
            type="button"
            onClick={() => setActiveTab('leaderboard')}
            className={`px-4 py-2.5 rounded-t-xl font-bold flex items-center gap-2 transition-colors ${
              activeTab === 'leaderboard'
                ? 'bg-slate-900 text-emerald-400 border-t-2 border-emerald-500 border-x border-slate-700'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Trophy className="w-4 h-4" />
            <span>{lang === 'hu' ? 'Ranglista' : 'Leaderboard'}</span>
          </button>

          {currentStats && (
            <button
              type="button"
              onClick={() => setActiveTab('save')}
              className={`px-4 py-2.5 rounded-t-xl font-bold flex items-center gap-2 transition-colors ${
                activeTab === 'save'
                  ? 'bg-slate-900 text-emerald-400 border-t-2 border-emerald-500 border-x border-slate-700'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Cloud className="w-4 h-4" />
              <span>{lang === 'hu' ? 'Eredmény Mentése' : 'Save Score'}</span>
            </button>
          )}

          <button
            type="button"
            onClick={() => setActiveTab('status')}
            className={`px-4 py-2.5 rounded-t-xl font-bold flex items-center gap-2 transition-colors ${
              activeTab === 'status'
                ? 'bg-slate-900 text-emerald-400 border-t-2 border-emerald-500 border-x border-slate-700'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <ShieldCheck className="w-4 h-4" />
            <span>{lang === 'hu' ? 'Kapcsolat infó' : 'Connection'}</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('sql')}
            className={`px-4 py-2.5 rounded-t-xl font-bold flex items-center gap-2 transition-colors ${
              activeTab === 'sql'
                ? 'bg-slate-900 text-emerald-400 border-t-2 border-emerald-500 border-x border-slate-700'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Copy className="w-4 h-4" />
            <span>{lang === 'hu' ? 'SQL Séma' : 'SQL Script'}</span>
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-5 sm:p-6 overflow-y-auto flex-1 text-slate-200 space-y-4">
          {/* TAB 1: LEADERBOARD */}
          {activeTab === 'leaderboard' && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-base font-bold text-white flex items-center gap-2">
                    <Trophy className="w-4 h-4 text-amber-400" />
                    {lang === 'hu' ? 'Supabase Eredménytábla' : 'Supabase Cloud Leaderboard'}
                  </h3>
                  <p className="text-xs text-slate-400">
                    {lang === 'hu'
                      ? 'Legjobb eredmények és éttermi quest teljesítések'
                      : 'Top diner scores & completed quest runs'}
                  </p>
                </div>
                <button
                  onClick={testConnection}
                  disabled={isLoading}
                  className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-slate-300 flex items-center gap-1.5 transition-colors border border-slate-700"
                >
                  <RefreshCw className={`w-3.5 h-3.5 ${isLoading ? 'animate-spin' : ''}`} />
                  <span>{lang === 'hu' ? 'Frissítés' : 'Refresh'}</span>
                </button>
              </div>

              <div className="divide-y divide-slate-800 rounded-2xl border border-slate-800 bg-slate-950/60 overflow-hidden">
                {leaderboard.length === 0 ? (
                  <div className="p-8 text-center text-slate-400 text-sm">
                    {lang === 'hu'
                      ? 'Még nincs mentett eredmény. Legyél te az első a ranglistán!'
                      : 'No scores recorded yet. Be the first to finish a quest!'}
                  </div>
                ) : (
                  leaderboard.map((item, idx) => (
                    <div
                      key={item.id || idx}
                      className="p-3.5 sm:p-4 flex items-center justify-between hover:bg-slate-900/50 transition-colors"
                    >
                      <div className="flex items-center gap-3">
                        <div
                          className={`w-7 h-7 rounded-full flex items-center justify-center font-black text-xs ${
                            idx === 0
                              ? 'bg-amber-500 text-slate-950 shadow-md shadow-amber-500/30'
                              : idx === 1
                              ? 'bg-slate-300 text-slate-950'
                              : idx === 2
                              ? 'bg-amber-700 text-white'
                              : 'bg-slate-800 text-slate-400'
                          }`}
                        >
                          {idx + 1}
                        </div>
                        <div>
                          <div className="font-bold text-white text-sm sm:text-base">
                            {item.player_name}
                          </div>
                          <div className="text-xs text-slate-400 flex items-center gap-2">
                            <span>Pontosság: {item.accuracy_percent}%</span>
                            <span>•</span>
                            <span>Max széria: {item.max_streak}x</span>
                          </div>
                        </div>
                      </div>

                      <div className="text-right">
                        <div className="font-black text-amber-400 text-base sm:text-lg">
                          +{item.score} pts
                        </div>
                        <div className="text-xs font-bold text-emerald-400">
                          ${item.wallet_dollars} earned
                        </div>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}

          {/* TAB 2: SAVE SCORE */}
          {activeTab === 'save' && currentStats && (
            <div className="space-y-4">
              <div className="p-4 rounded-2xl bg-emerald-950/30 border border-emerald-500/30 space-y-2">
                <h3 className="font-bold text-emerald-300 text-sm">
                  {lang === 'hu' ? 'Aktuális Játékeredményed' : 'Your Current Game Score'}
                </h3>
                <div className="grid grid-cols-3 gap-2 text-center">
                  <div className="p-2 rounded-xl bg-slate-900/80 border border-slate-800">
                    <div className="text-xs text-slate-400">Összpontszám</div>
                    <div className="text-lg font-black text-amber-400">{currentStats.score} pts</div>
                  </div>
                  <div className="p-2 rounded-xl bg-slate-900/80 border border-slate-800">
                    <div className="text-xs text-slate-400">Egyenleg</div>
                    <div className="text-lg font-black text-emerald-400">${currentStats.walletDollars}</div>
                  </div>
                  <div className="p-2 rounded-xl bg-slate-900/80 border border-slate-800">
                    <div className="text-xs text-slate-400">Elsőre helyes</div>
                    <div className="text-lg font-black text-indigo-400">
                      {currentStats.firstTryCorrect} / {currentStats.totalAnswered}
                    </div>
                  </div>
                </div>
              </div>

              <form onSubmit={handleSaveScore} className="space-y-3">
                <div>
                  <label className="block text-xs font-bold text-slate-300 mb-1.5">
                    {lang === 'hu' ? 'Add meg a neved a ranglistához:' : 'Enter your player name:'}
                  </label>
                  <input
                    type="text"
                    required
                    value={playerName}
                    onChange={(e) => setPlayerName(e.target.value)}
                    placeholder={lang === 'hu' ? 'Pl. Kovács Anna' : 'e.g. Gordon R.'}
                    className="w-full px-4 py-3 rounded-xl bg-slate-950 border border-slate-700 text-white placeholder-slate-500 focus:outline-hidden focus:border-emerald-500 text-sm font-medium"
                  />
                </div>

                <button
                  type="submit"
                  disabled={isLoading || !playerName.trim()}
                  className="w-full py-3.5 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 disabled:opacity-50 text-white font-bold text-sm shadow-lg shadow-emerald-900/30 flex items-center justify-center gap-2 transition-all cursor-pointer"
                >
                  <Cloud className="w-4 h-4" />
                  <span>
                    {isLoading
                      ? lang === 'hu'
                        ? 'Mentés folyamatban...'
                        : 'Saving...'
                      : lang === 'hu'
                      ? 'Mentés a Supabase Adatbázisba'
                      : 'Save to Supabase Database'}
                  </span>
                </button>
              </form>

              {saveSuccessMsg && (
                <div className="p-3 rounded-xl bg-emerald-900/40 border border-emerald-500/40 text-emerald-300 text-xs font-semibold flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                  <span>{saveSuccessMsg}</span>
                </div>
              )}
            </div>
          )}

          {/* TAB 3: CONNECTION STATUS */}
          {activeTab === 'status' && (
            <div className="space-y-4 text-sm">
              <div className="p-4 rounded-2xl bg-slate-950/80 border border-slate-800 space-y-3">
                <div className="flex items-center justify-between pb-3 border-b border-slate-800">
                  <span className="text-slate-400 text-xs">Supabase URL:</span>
                  <span className="font-mono text-xs text-emerald-300">{SUPABASE_URL}</span>
                </div>
                <div className="flex items-center justify-between pb-3 border-b border-slate-800">
                  <span className="text-slate-400 text-xs">Project Ref:</span>
                  <span className="font-mono text-xs text-indigo-300">hdxdnrxqktxszikamnbu</span>
                </div>
                <div className="flex items-center justify-between pb-3 border-b border-slate-800">
                  <span className="text-slate-400 text-xs">Hitelesítés:</span>
                  <span className="text-xs text-slate-300 font-medium">Anon JWT Key (kliensoldali)</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-slate-400 text-xs">Kapcsolat állapota:</span>
                  <span className="text-xs font-bold text-emerald-400 flex items-center gap-1.5">
                    <CheckCircle2 className="w-4 h-4" />
                    Csatlakoztatva (OK)
                  </span>
                </div>
              </div>

              <div className="p-4 rounded-2xl bg-indigo-950/30 border border-indigo-500/30 space-y-1.5">
                <h4 className="font-bold text-indigo-300 text-xs uppercase tracking-wider">
                  {lang === 'hu' ? 'Adatbázis Integráció' : 'Database Integration'}
                </h4>
                <p className="text-xs text-slate-300 leading-relaxed">
                  {lang === 'hu'
                    ? 'Az alkalmazás automatikusan szinkronizálja az elért pontszámokat, éttermi egyenlegeket és a helyes válaszokat a megadott Supabase projekt tábláival.'
                    : 'The app automatically synchronizes completed scores, wallet earnings, and student accuracy with the configured Supabase project.'}
                </p>
              </div>
            </div>
          )}

          {/* TAB 4: SQL SCRIPT */}
          {activeTab === 'sql' && (
            <div className="space-y-3 text-xs">
              <div className="flex items-center justify-between">
                <p className="text-slate-400">
                  {lang === 'hu'
                    ? 'Másold be a Supabase SQL Editorba a tábla létrehozásához:'
                    : 'Paste this into your Supabase SQL Editor to create the table:'}
                </p>
                <button
                  type="button"
                  onClick={copySql}
                  className="px-3 py-1 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs flex items-center gap-1.5 transition-colors"
                >
                  {copiedSql ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedSql ? (lang === 'hu' ? 'Másolva!' : 'Copied!') : (lang === 'hu' ? 'Másolás' : 'Copy SQL')}</span>
                </button>
              </div>

              <pre className="p-4 rounded-2xl bg-slate-950 border border-slate-800 text-emerald-300 font-mono text-[11px] overflow-x-auto leading-relaxed select-all">
                {sqlSchemaScript}
              </pre>
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="p-4 bg-slate-950 border-t border-slate-800 flex justify-end">
          <button
            type="button"
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-bold text-xs transition-colors"
          >
            {lang === 'hu' ? 'Bezárás' : 'Close'}
          </button>
        </div>
      </div>
    </div>
  );
};
